version: '3.9'

services:
  redis:
    build: ./redis/.
    container_name: redis_container
    ports:
      - 6379:6379
    restart: on-failure
    volumes:
      - .cache:/data
    
  golang:
    container_name: golang_container
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    environment:
      - PORT=${PORT}
      - STAGE=${STAGE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: on-failure
    depends_on:
      - redis

volumes:
  redis: {}